FROM node:22-alpine 

WORKDIR /app

COPY package*.json .
RUN npm ci

COPY . .

CMD ["npm", "start"]

# docker build -t react-app:dev -f Dockerfile.dev .
# docker run --rm -d -p 3000:3000 react-app:dev
# docker run --rm -d -p 3000:3000 -v ./public:/app/public -v ./src:/app/src  react-app:dev

